---
title: "Exploding Boxplots"
author: "Homer White"
date: "2018-01-31"
output:
  flexdashboard::flex_dashboard:
    source_code: embed
    storyboard: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bpexploder)
library(ggplot2)
data("m111survey", package = "tigerstats")
```

### Have a look at the `iris` data.{data-commentary-width=450}

```{r echo = FALSE}
bpexploder(data = iris,
           settings = list(
             groupVar = "Species",
             levels = levels(iris$Species),
             yVar = "Petal.Length",
             tipText = list(
               Petal.Length = "Petal Length"
             ),
             aspect = 1.5)
           )
```

***

Here's the code:

```{r eval = FALSE}
bpexploder(data = iris,
           settings = list(
             groupVar = "Species",
             levels = levels(iris$Species),
             yVar = "Petal.Length",
             tipText = list(
               Petal.Length = "Petal Length"
             ),
             aspect = 1.5)
           )
```


### Modest customization is possible. {data-commentary-width=550}

<p id="ref2" style="width: 60%"></p>


```{r echo = FALSE}
bpexploder(data = chickwts,
           settings = list(
             yVar = "weight",
             # default NULL would make make one plot for yVar
             groupVar = "feed",
             levels = levels(with(chickwts,
                                  reorder(feed, weight, median))),
             # you could adjust the group labels ...
             levelLabels = NULL,
             # ... and the colors for each group:
             levelColors = RColorBrewer::brewer.pal(6, "Set3"),
             yAxisLabel = "6-week weight (grams)",
             xAxisLabel = "type of feed",
             tipText = list(
               # as many os you like of:
               # variableName = "desired tool-tip label"
               # leave tipText at NULL for no tips
               weight = "weight"),
             # set width relative to grandarent element of svg image:
             relativeWidth = 0.6
             #referenceId = "ref2"
             )
           )
```

***

Here's the code.

```{r eval = FALSE}
bpexploder(data = chickwts,
           settings = list(
             yVar = "weight",
             # default NULL would make make one plot for yVar
             groupVar = "feed",
             levels = levels(with(chickwts,
                                  reorder(feed, weight, median))),
             # you could adjust the group labels ...
             levelLabels = NULL,
             # ... and the colors for each group:
             levelColors = RColorBrewer::brewer.pal(6, "Set3"),
             yAxisLabel = "6-week weight (grams)",
             xAxisLabel = "type of feed",
             tipText = list(
               # as many os you like of:
               # variableName = "desired tool-tip label"
               # leave tipText at NULL for no tips
               weight = "weight"),
             # set width relative to grandarent element of svg image:
             relativeWidth = 0.6)
           )
```

### Another example. {data-commentary-width=500}


```{r eval = TRUE, echo = FALSE}
survey <- tigerstats::m111survey
bpexploder(data = survey,
           settings = list(
             yVar = "fastest",
             groupVar = "seat",
             levelLabels = c("front", "middle", "back"),
             yAxisLabel = "fastest speed (mph)",
             xAxisLabel = "seating preference",
             tipText = list(
               sex = "sex",
               height = "height",
               fastest = "speed"),
             relativeWidth = 1)
           )
```


***

Here's the code:

```{r eval = FALSE}
survey <- tigerstats::m111survey
bpexploder(data = survey,
           settings = list(
             yVar = "fastest",
             groupVar = "seat",
             levelLabels = c("front", "middle", "back"),
             yAxisLabel = "fastest speed (mph)",
             xAxisLabel = "seating preference",
             tipText = list(
               sex = "sex",
               height = "height",
               fastest = "speed"),
             relativeWidth = 1)
           )
```

### ggplot. {data-commentary-width=500}


```{r eval = TRUE, echo = FALSE}
ggplot(m111survey, aes(x = sex, y = fastest)) + geom_boxplot()
```


***

Here's the code:

```{r eval = FALSE}
ggplot(m111survey, aes(x = sex, y = fastest)) + 
  geom_boxplot()
```

